logo = true
logoText = "Unikraft"
logoType = "short"
description = "Extreme Specialization for Security and Performance"

themeOptions = ["light", "dark"]

useFaviconGenerator = true # https://www.favicon-generator.org/

enableTocSwitch = true
enableLandingBackground = false
enableSearch = true
enableSearchHighlight = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = true
enableToc = true
enableMenu = true
enableNavbar = true

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

editBaseURL = "https://github.com/unikraft/docs/edit/staging/content/en"
github = "https://github.com/unikraft/docs"

# comment
enableComment = false
disqus_shortname = ""
commento = false

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
